"""title column userfilm

Revision ID: 01da648babde
Revises: ac4d59baae68
Create Date: 2018-06-08 17:39:53.860564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01da648babde'
down_revision = 'ac4d59baae68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_film_titleId', table_name='film')
    op.add_column('user__film', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__film', 'title')
    op.create_index('ix_film_titleId', 'film', ['titleId'], unique=False)
    # ### end Alembic commands ###
