"""rename film on post

Revision ID: 5161aa79ff49
Revises: f97229dd31e5
Create Date: 2018-05-04 18:03:55.061782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5161aa79ff49'
down_revision = 'f97229dd31e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.String(64), nullable=True),
    sa.Column('genres', sa.String(length=255), nullable=True),
    sa.Column('userRating', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_index(op.f('ix_post_userRating'), 'post', ['userRating'], unique=False)
    op.create_index(op.f('ix_post_year'), 'post', ['year'], unique=False)
    op.drop_index('ix_film_timestamp', table_name='film')
    op.drop_index('ix_film_userRating', table_name='film')
    op.drop_index('ix_film_year', table_name='film')
    op.drop_table('film')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('year', sa.VARCHAR(64), nullable=True),
    sa.Column('genres', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('userRating', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_film_year', 'film', ['year'], unique=False)
    op.create_index('ix_film_userRating', 'film', ['userRating'], unique=False)
    op.create_index('ix_film_timestamp', 'film', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_post_year'), table_name='post')
    op.drop_index(op.f('ix_post_userRating'), table_name='post')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
