"""add username column uf

Revision ID: a5e1e0042c0e
Revises: 01da648babde
Create Date: 2018-06-08 18:19:23.569298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e1e0042c0e'
down_revision = '01da648babde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__film', sa.Column('username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__film', 'username')
    # ### end Alembic commands ###
