"""userRating column

Revision ID: a746ecf008e5
Revises: 22e3f5918939
Create Date: 2018-05-03 18:15:49.001376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a746ecf008e5'
down_revision = '22e3f5918939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('userRating', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_film_userRating'), 'film', ['userRating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_film_userRating'), table_name='film')
    op.drop_column('film', 'userRating')
    # ### end Alembic commands ###
