"""timestamp column

Revision ID: ac4d59baae68
Revises: c6cc722da003
Create Date: 2018-06-06 16:49:01.130135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4d59baae68'
down_revision = 'c6cc722da003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__film', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user__film_timestamp'), 'user__film', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user__film_timestamp'), table_name='user__film')
    op.drop_column('user__film', 'timestamp')
    # ### end Alembic commands ###
