"""user_film class

Revision ID: c6cc722da003
Revises: 827fe25743be
Create Date: 2018-06-06 14:46:14.254332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6cc722da003'
down_revision = '827fe25743be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_film')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_film',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('film_id', sa.INTEGER(), nullable=True),
    sa.Column('userRating', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user__film')
    # ### end Alembic commands ###
