"""create table film and relationships m-m

Revision ID: da8512962f69
Revises: 5161aa79ff49
Create Date: 2018-05-04 18:47:45.620433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8512962f69'
down_revision = '5161aa79ff49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titleId', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.DateTime(), nullable=True),
    sa.Column('genres', sa.String(length=255), nullable=True),
    sa.Column('avgRating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_avgRating'), 'film', ['avgRating'], unique=False)
    op.create_index(op.f('ix_film_titleId'), 'film', ['titleId'], unique=False)
    op.create_table('user_film',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_film')
    op.drop_index(op.f('ix_film_titleId'), table_name='film')
    op.drop_index(op.f('ix_film_avgRating'), table_name='film')
    op.drop_table('film')
    # ### end Alembic commands ###
