"""timestamp column film

Revision ID: f97229dd31e5
Revises: 9bf98b4c2dfe
Create Date: 2018-05-04 15:29:34.050014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97229dd31e5'
down_revision = '9bf98b4c2dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_film_timestamp'), 'film', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_film_timestamp'), table_name='film')
    op.drop_column('film', 'timestamp')
    # ### end Alembic commands ###
